### ISSUE TITLE
Coding conventions page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#103]
1. Link to Google's guide for R is broken

2. Link to Google's style guide for C++ is broken

3. I can't see the point of this line:
bash: line 1: pep8: command not found

**Comment by ageorgou** [comment]
Coding conventions -- updated links:
    - PEP8: https://www.python.org/dev/peps/pep-0008/
    - Google R style: https://google.github.io/styleguide/Rguide.xml
    - Google C++ style: https://google.github.io/styleguide/cppguide.html

Linters:
    - "These are called linters" -> Missing "."
    - `pep8` not installed when building pages

**Comment by dpshelio** [comment]
Maybe to mention about 
 - [Black](https://black.readthedocs.io/en/stable/)
 - [pep8speaks](https://pep8speaks.com/) vs linting on CI.
 - hooks (pre-commits)

**Comment by dpshelio** [comment]
`input` to `value`?
