### ISSUE TITLE
Design page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#106]
1. In "Replace add-hoc structure with user defined classes", why is the import statement in the class definition rather than at the top of the file?

2. In "Replace function with a method", should not the abs() function be used to be consistent with previous pages? 

3. In "Replace global variable with class and member" the new code is much bigger than the old code. Obviously the new code is more generic than the old code, but if the only place the old code was used is in the example, creating a new class just to handle it seems like overkill. But of course there may be other places in the code we haven't seen which require this functionality, in which case it makes more sense.

**Comment by dpshelio** [comment]
- `type` to `species`, `family`, `kind`
