### ISSUE TITLE
Exceptions page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#116]
1. Text says "Doing this is as simple as inheriting from Exception:" but the code shows us inheriting from `ArithmeticError`.

2. Typo "specfic" should be "specific"

**Comment by ageorgou** [comment]
1. Say what `getmro` shows you... (or don't show it all)

1. [typo] In `MyCustomErrorType`: "cateory" -> "category" (in `__str__`)

1. Bare `except`: Add a warning ("However, this can be dangerous!) before the explanation of why you shouldn't do it.

1. Maybe mention the phrase "easier to ask forgiveness than permission" (https://docs.python.org/3/glossary.html#term-eafp) when discussing coding style and control flow using exceptions?

1. Mention `raise from` syntax when discussing error handling (at the end of the chapter)? It could be useful for tracking errors in complex code.
