### ISSUE TITLE
Greenmap example broken again

### ISSUE THREAD

**Issue by ageorgou** [UCL/rsd-engineeringcourse#182]
The ["greenmap" example](http://github-pages.ucl.ac.uk/rsd-engineeringcourse/ch00python/010exemplar.html) from the first lesson does not run. It used to use Google Maps, but they disabled access without a key. We switched to Yandex for last year, but now that's done the same. From memory, all the options either needed a key (which we didn't want to make public, and sometimes also required a card to charge to) or had to be self-hosted.

If we can't find a geocoding/map API that does not require a key, we'll have to use a different example. The main points that the current example is showcasing (without explaining) are
- use of libraries (including plotting)
- writing functions
- getting data from a web source

A replacement doesn't need to be similar but should probably hit the same spots.

**Comment by dpshelio** [comment]
We could use [cartopy](https://github.com/SciTools/cartopy) and measure green from the data provided there... but that then it doesn't includes the querying the website bit, unless we find a cities/location api.

**Comment by Saransh-cpp** [comment]
This was fixed in the PR linked above but the issue was never closed.
