### ISSUE TITLE
Remove links to old CDT Medical Imaging

### ISSUE THREAD

**Issue by MattClarkson** [UCL/rsd-engineeringcourse#184]

**Comment by MattClarkson** [comment]
I thought about changing the URL to point to the new i4Health CDT, but decided against this, as its not really relevant. People are now registering from all over college.  Students would be expected to find the module in the UCL Module Catalogue, or by reputation within their department. So, the link itself is unnecessary.

**Comment by Saransh-cpp** [comment]
Fixed in the commit referenced above!
