### ISSUE TITLE
Mobile view doesn't show the menu of the lessons

### ISSUE THREAD

**Issue by dpshelio** [UCL/rsd-engineeringcourse#212]
![Screenshot_20220906-135702.png](https://user-images.githubusercontent.com/963242/188641203-20d7d5ff-0fa7-432f-89fe-d24dd54dcf6d.png)

**Comment by Saransh-cpp** [comment]
For me it is combined with the UCL hamburger menu. Opening that hamburger shows both the menus stacked vertically -

![WhatsApp Image 2024-08-12 at 4 44 15 PM](https://github.com/user-attachments/assets/01a47afe-82a4-4b45-84dc-2341ea2802af)

**Comment by dpshelio** [comment]
Oh! it does in Firefox (mobile and mobile view on desktop) too. We can close it then!
