### ISSUE TITLE
Check packaging information is up to date on notes and exercises 

### ISSUE THREAD

**Issue by dpshelio** [UCL/rsd-engineeringcourse#237]
Packaging explanation has been updated to use `pyproject.toml` though some exercises may not have it([from week 7](https://github.com/UCL-COMP0233-22-23/RSE-Classwork/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aweek07).
We need to update the explanations, add links to documentation such as [python's packaging guide](https://packaging.python.org/en/latest/) and [pyopensci's packaging guide](https://www.pyopensci.org/python-package-guide/). Maybe even to teach [`hatch`](https://www.pyopensci.org/blog/pyos-community-news-aug-2024.html).

**Comment by Saransh-cpp** [comment]
Hi @dpshelio! I don't have access to the exercises. Would it be possible for you to add me to that organization or the repository so that I can edit the issue comments? Thanks!

**Comment by dpshelio** [comment]
You've got access now.

**Comment by Saransh-cpp** [comment]
Thanks, @dpshelio! I think I was added to the [wrong](https://github.com/UCL-ARC-RSEing-with-Python) organisation tho 😬 The exercises are in https://github.com/UCL-COMP0233-22-23
