### ISSUE TITLE
Dead link in 00pythons.ipynb

### ISSUE THREAD

**Issue by fepegar** [UCL/rsd-engineeringcourse#49]
This one, about IPython videos:
https://github.com/UCL/rsd-engineeringcourse/blob/master/ch00python/00pythons.ipynb?short_path=9afdcc2#L250

**Comment by dpshelio** [comment]
Gracias @fepegar  - we will fix that (I think I removed them from the [basic course]( https://github.com/UCL-RITS/doctoral-programming-intro/) - which is the same for the first few lessons).

**Comment by fepegar** [comment]
De nada @dpshelio! I'll report any other issues I find until the day of the exam. I hope it helps.

**Comment by fepegar** [comment]
Same broken link in `015variables.ipynb`.

**Comment by sgrieve** [comment]
Resolved in PR #43.
