### ISSUE TITLE
Dead link in 010exemplar.ipynb

### ISSUE THREAD

**Issue by fepegar** [UCL/rsd-engineeringcourse#50]
Link to Software Carpentry example shoud be
http://swcarpentry.github.io/python-novice-inflammation/01-numpy/

instead of
http://swcarpentry.github.io/python-novice-inflammation/01-numpy.html

**Comment by fepegar** [comment]
Same problem with same link in `015variables.ipynb`: https://github.com/UCL/rsd-engineeringcourse/blob/master/ch00python/015variables.ipynb?short_path=2d0357b#L183

**Comment by sgrieve** [comment]
Resolved in PR #43.
