### ISSUE TITLE
broken link in Introduction page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#57]
The link to the videos about the notebook is broken

**Comment by dpshelio** [comment]
That seems it was fixed by af7b975, but it didn't propagate to the site... There must be something wrong with Travis then.

**Comment by dpshelio** [comment]
And here it is the problem:
![screenshot from 2018-08-21 11-40-37](https://user-images.githubusercontent.com/963242/44397154-32458000-a537-11e8-8305-404c4042257f.png)
Why travis get this green... is just a mystery.

**Comment by ageorgou** [comment]
The fix (also updated in #111) has now propagated to the site. Closing.
