### ISSUE TITLE
Issues with "An example Python data analysis notebook" page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#58]
I'm not sure how useful this page is. I think it might just end up confusing people. An introductory program should be nice and simple. And I got GeocoderQuotaExceeded error when I tried this before, so maybe we should use something else which is simple and guaranteed to work??!!

Maybe add a note at the beginning that this is just to outline some of Python's capabilities, but that we will go through them afterwards in detail. I know it says this at the bottom but we should say earlier too.

The link to the carpentry course is broken.

**Comment by ageorgou** [comment]
I believe this was fixed in #123.

@mattgillucl and @dpshelio, let me know if you get the chance to check and are not satisfied.
