### ISSUE TITLE
"The Boids!" page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#67]
Link to saved animation MP4 does not work.

There are lines like:
positions=new_flock(100, np.array([100,900]), np.array([200,1100]))
velocities=new_flock(100, np.array([0,-20]), np.array([10,20]))

I think we should be explicitly explaining why these particular numbers were chosen. It's not at all clear to me.

"We'll need a matrix giving the distances between each bird. " -> should be boid not bird
"Match speed with nearby birds" -> likewise

**Comment by dpshelio** [comment]
b149927 fixes it.

**Comment by mattgillucl** [comment]
There still seem to be magic numbers floating around judging by the update

**Comment by ageorgou** [comment]
@mattgillucl There are indeed numbers in the code that could be replaced by variables, but I think I explained them all in the text of the notebook. Is there something that I have missed?

**Comment by mattgillucl** [comment]
Oh yes. No problem!
