### ISSUE TITLE
Update Travis setup

### ISSUE THREAD

**Issue by dpshelio** [UCL/rsd-engineeringcourse#69]
As shown in #57 the push to the website is not working. Travis offers now better ways to do [deploy in a new branch](https://docs.travis-ci.com/user/deployment/pages/).

We should also [update to github apps](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/)

**Comment by dpshelio** [comment]
- First bit changed on 4b86e78
- second bit to test whenever :octocat: is not sick anymore...

**Comment by Saransh-cpp** [comment]
Travis is no longer used in the repo. Closing this!
