### ISSUE TITLE
Introduction to version control page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#70]
This page starts off using Jupyter notebook but at the end says to use a text editor. I wonder if it would be better to get the students to use the command line instead. Then they should be able to see the nice colour formatting of git. I think using the notebook might confuse them?

**Comment by mattgillucl** [comment]
IPython should read Jupyter anyway.
The pre-requisite page says "You are required to bring your own laptop to the course as the classrooms we are using do not have desktop computers." If so we should be OK.

**Comment by dpshelio** [comment]
Solved in various PRs.
