### ISSUE TITLE
Installing Libraries page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#93]
1. link to Anaconda web site gives a page not yet exist error.

2. at the end - practicing should be practising

**Comment by ageorgou** [comment]
1. Installing Geopy using Pip:
  - start -> all programs: Capitalise
  - terminal: Ditto
  - "The computer will install the package automatically from PyPI." -> I would change to "The computer will install the package *and its dependencies* automatically from PyPI (a repository of packages, which we'll talk about later)."

1. Where do these libraries go?: Comment next to `sys.path` is (no longer?) applicable

1. Libraries not in PyPI: Is it better to suggest `python setup.py install` or `pip install .`? The latter is more consistent with the previous sections, and I believe it works with recent-ish versions of `pip`?

1. Overall: Should we mention environments (either the Python implementations, or as a more general concept)?
