### ISSUE TITLE
Documentation page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#97]
1. In the line "Here's some Sphinx-generated output and the corresponding source code" the link to the source code doesn't work.

2. breathe link is now https://breathe.readthedocs.io/en/latest/

3. Roxygen link goes to a not-very-helpful RStudio page

4. numpydoc Sphinx extension link is now https://numpydoc.readthedocs.io/en/latest/

5. docstring Star Trek example does not have closing `"""`

6. The sphinx-quickstart link is broken.

**Comment by ageorgou** [comment]
1. One thing missing from this page is why you would want to write documentation
1. Comment-based Documentation tools: Lots of periods missing
1. Write some docstrings: Missing `"""` to close docstring

**Comment by dpshelio** [comment]
Move it after writing libraries.

**Comment by dpshelio** [comment]
Good place to introduce doctests.
