### ISSUE TITLE
Software Project Management (agile and waterfall) page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#98]
1. No Silver Bullet article - also see chapter 16 of "The Mythical Man-Month: Essays on Software Engineering" by Frederick Brooks

2. Link to Prof. Anthony Finkelstein is broken

3. The Agile manifesto - Folwer should be Fowler

**Comment by ageorgou** [comment]
Maybe add a link to explain [code smells](https://en.wikipedia.org/wiki/Code_smell)?
