### ISSUE TITLE
 Software Licensing page

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#99]
1. In the line "Here we attempt to give some basic advice on choosing a license for your software" license should be licence.

2. Link to O'Reilly book is broken. And maybe it would be better to link to their website if possible rather than Amazon. If I have chosen the right book the link is http://shop.oreilly.com/product/9780596005818.do

3. Sentence "Your department, or UCL, may have policies about applying licenses to code you create" - license should be licence.

4. In fact throughout this page "license" should be "licence" except for Creative Commons By Attribution license (US usage). In British English licence is a noun and license a verb (like advice and advise).

5. Link to Continuum timed out

6. Link to page on Software Sustainability Institute site is broken

**Comment by ageorgou** [comment]
Patents: "Very roughly, if a you want" -> delete "a".
